Bump Max Gas For Simulation
cowprotocol/services pull request #1361
Opened 2023-03-21 12:42 UTC by nlordell

This PR is a follow up to #1354 

Specifically, for EIP-1559, an account needs to have sufficient ETH for `max_fee_per_gas` for the transaction to be executable. This PR changes the `gas_price_for_simulation` to be correct for EIP-1559.

This implementation is not ideal, since the `max_fee_per_gas` is now much higher than it needs to be (see https://github.com/cowprotocol/services/issues/1360 and https://github.com/cowprotocol/services/pull/1354#discussion_r1141915999).

### Test Plan

Adjusted unit test passes.

2023-03-21 13:01 UTC, fleupold requested changes
I believe that with this change, we are very close to the behaviour of the code before https://github.com/cowprotocol/services/pull/1354 but now with a hacky helper method that does some really hard to reason about math.

Before we were already bumping the gas price (which adjusts max_fee_per_gas and max_priority_fee). My suggestion would be to also make `bump` also increase the base fee. 

The main change that I believe is needed to actually fix this issue is to make the simulation use the `max_gas_price` rather than the `effective_gas_price`

2023-03-21 13:09 UTC, nlordell commented
> The main change that I believe is needed to actually fix this issue is to make the simulation use the `max_gas_price` rather than the `effective_gas_price`

Oh, I was surprised that we aren't already simulating with EIP-1559 gas parameters TBH. Definitely an issue.

I do think we need to still bump `max_gas_price` ATM though. I have a different PR implementing ideas from #1360 that I think will work better (i.e. come up with an upper bound for `max_fee_per_gas` upfront and not over-estimate it for simulations).

2023-03-21 14:34 UTC, fleupold commented
> I do think we need to still bump max_gas_price ATM though

Yes, but reverting #1354 would be better in my opinion, because we now have some hard to understand one off gas price manipulation function which we are changing again to do almost what the code was doing before (a sign that it's not easy to understand what exactly we are trying to achieve with it). 

Before, we were bumping the gas price in https://github.com/cowprotocol/services/blob/c3b758cc5689ca56f7b1f6b07d7a00ff35fc87f1/crates/solver/src/settlement_ranker.rs#L151 which does also bump `max_fee_per_gas` by the specified factor (just not the base fee and therefore the effective gas fee, which is defined as `min(base_fee + tip, max_fee_per_gas)` is not bumped).

@sunce mentioned in the original PR that the node executes the `eth_estimateGas` with `effective_gas_price` to check if account balance is enough to execute the transaction.

I think the behavior is node dependent. Take this request for instance, for which the sending account has enough `baseFee + tip`, but not enough maxFeePerGas:

```
{"id": 1, "jsonrpc": "2.0", "method": "eth_estimateGas", "params": [{"to": "0xE0B3700e0aadcb18ed8d4BFF648Bc99896a18ad1", "from": "0xE0B3700e0aadcb18ed8d4BFF648Bc99896a18ad1", "maxFeePerGas": "0x9184e72a000", "maxPriorityFeePerGas": "0x1", "data": "0x"}]}
```

It works on our nethermind nodes (even if I use a legacy gasPrice that is higher than my balance), but Infura rejects it based on `maxFeePerGas`.

I think we might have to add a post processing check to filter out settlements for which `max_fee_per_gas * gas_limit > EOA balance`

2023-03-22 12:57 UTC, nlordell commented
Superseded by #1363 and #1366

2023-03-23 10:19 UTC, closed without merging

2023-03-27 13:12 UTC, sunce86 commented
> > I do think we need to still bump max_gas_price ATM though
> 
> Yes, but reverting #1354 would be better in my opinion, because we now have some hard to understand one off gas price manipulation function which we are changing again to do almost what the code was doing before (a sign that it's not easy to understand what exactly we are trying to achieve with it).
> 
> Before, we were bumping the gas price in
> 
> https://github.com/cowprotocol/services/blob/c3b758cc5689ca56f7b1f6b07d7a00ff35fc87f1/crates/solver/src/settlement_ranker.rs#L151
> 
> which does also bump `max_fee_per_gas` by the specified factor (just not the base fee and therefore the effective gas fee, which is defined as `min(base_fee + tip, max_fee_per_gas)` is not bumped).
> @sunce mentioned in the original PR that the node executes the `eth_estimateGas` with `effective_gas_price` to check if account balance is enough to execute the transaction.
> 
> I think the behavior is node dependent. Take this request for instance, for which the sending account has enough `baseFee + tip`, but not enough maxFeePerGas:
> 
> ```
> {"id": 1, "jsonrpc": "2.0", "method": "eth_estimateGas", "params": [{"to": "0xE0B3700e0aadcb18ed8d4BFF648Bc99896a18ad1", "from": "0xE0B3700e0aadcb18ed8d4BFF648Bc99896a18ad1", "maxFeePerGas": "0x9184e72a000", "maxPriorityFeePerGas": "0x1", "data": "0x"}]}
> ```
> 
> It works on our nethermind nodes (even if I use a legacy gasPrice that is higher than my balance), but Infura rejects it based on `maxFeePerGas`.
> 
> I think we might have to add a post processing check to filter out settlements for which `max_fee_per_gas * gas_limit > EOA balance`

I suspect some nodes are ignoring even the `max_fee_per_gas`, for example:
https://github.com/openethereum/openethereum/blob/main/crates/ethcore/src/executive.rs#L1104-L1108
(or this might be a bug or a standard spec for `eth_estimateGas` has changed in the meantime)

Overall, I don't think the time spent into investigating this is worth it. We should just add an explicit balance check and stop relying on `estimateGas`.
@nlordell

2023-03-27 14:46 UTC, nlordell commented
#1367 changes the logic to do an explicit balance check instead of relying on `eth_estimateGas` behaviour.