Make u256 parsing more lenient
cowprotocol/services pull request #781
Opened 2022-11-15 14:26 UTC by vkgnosis

When investigating why `0x19D3364A399d251E894aC732651be8B0E4e85001` was classified as a bad token I found that `balanceOf` for this contract returns 4096 bytes instead of the expected 32 bytes for a u256. The balance is correctly encoded in the first 32 bytes but there are extra all 0 bytes at the end.

When doing a normal `balanceOf` view call through a node the extra data is ignored but in when parsing the u256 from the `trace_call` response we check for strict equality of the bytes length which fails. This commit makes this check more lenient in order to not fail for these kind of addresses.

I do not yet know where the extra data comes from. This is not a quirk of `trace_call`. From the transport logs I can see that for the the view call the data is there too, it is just ignored. I guess in some ethereum standard it says that extra unexpected data should be ignored? I suspect it is some quirk of the compiler they used for this contract. The abi is clear that it should be a u256.

### Test Plan

Tested manually

2022-11-15 15:01 UTC, MartinquaXD approved these changes

2022-11-15 16:10 UTC, nlordell approved these changes
Code looks good to me.

I double checked with the Yearn team if this is expected. It looks like a Vyper contract quirk.

AFAIK, this is only accepted in Solidity ABI because it uses a `CALL` opcode with explicit return data length parameter (meaning read up to N bytes from return data) for these types of calls.

In theory though, this is not standard Solidity ABI...

2022-11-15 16:20 UTC, nlordell commented
@poolpitako confirmed that this is, indeed, a Vyper contract issue.

However, this won't work with our GPv2 Settlement contract because:
```solidity
            assembly {
                case 0 {
                    // ...
                }
                // Standard ERC20 transfer returning boolean success value.
                case 32 {
                    // ...
                }
                default {
                    revertWithMessage(31, "GPv2: malformed transfer result")
                }
            }
```

So I actually think we shouldn't merge this change as we don't support actually transferring out this token from the Settlement contract.

2022-11-15 16:20 UTC, nlordell requested changes
❌

2022-11-17 09:36 UTC, closed without merging

2023-01-25 16:14 UTC, sunce86 commented
Another discussion: https://cowservices.slack.com/archives/C0375NV72SC/p1674661229317249